"""Agent API endpoints for receiving check results from remote servers."""
import json
from datetime import datetime
from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, status, UploadFile, File
from sqlalchemy.orm import Session
from pydantic import BaseModel

from app.core.database import get_db
from app.core.config import settings
from app.models.asset import Asset
from app.models.assessment import Assessment, AssessmentStatus
from app.models.checklist import ChecklistItem

router = APIRouter()


class CheckResult(BaseModel):
    """Single check result from agent."""
    item_code: str
    status: str  # pass, fail, na
    evidence: Optional[str] = None
    check_command: Optional[str] = None
    remediation_command: Optional[str] = None


class AgentReport(BaseModel):
    """Report from agent containing multiple check results."""
    asset_name: str
    asset_type: str  # windows, unix
    hostname: Optional[str] = None
    ip_address: Optional[str] = None
    results: List[CheckResult]
    agent_version: str = "1.0.0"


class AgentReportResponse(BaseModel):
    """Response after processing agent report."""
    success: bool
    asset_id: int
    processed: int
    created: int
    updated: int
    errors: List[str]


@router.post("/report", response_model=AgentReportResponse)
async def receive_agent_report(
    report: AgentReport,
    api_key: Optional[str] = None,
    db: Session = Depends(get_db)
):
    """
    Receive vulnerability check results from agent.

    This endpoint can be called by agents running on target servers
    to submit their check results.
    """
    return await process_agent_report(report, db)


@router.get("/checklist/{asset_type}")
async def get_checklist_for_agent(
    asset_type: str,
    db: Session = Depends(get_db)
):
    """
    Get checklist items for agent to know what to check.

    Returns a simplified list of check items for the specified asset type.
    """
    items = db.query(ChecklistItem).filter(
        ChecklistItem.asset_type == asset_type.lower()
    ).all()

    return [
        {
            "item_code": item.item_code,
            "title": item.title,
            "check_method": item.check_method,
            "pass_criteria": item.pass_criteria,
            "fail_criteria": item.fail_criteria,
        }
        for item in items
    ]


@router.post("/upload", response_model=AgentReportResponse)
async def upload_agent_report(
    file: UploadFile = File(...),
    db: Session = Depends(get_db)
):
    """
    Upload a JSON report file from agent.

    Use this endpoint when direct network connectivity is not available.
    Upload the kisa-report.json file generated by the agent script.
    """
    # Validate file type
    if not file.filename.endswith('.json'):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Only JSON files are accepted"
        )

    try:
        # Read and parse JSON with multiple encoding support
        content = await file.read()

        # Try different encodings (PowerShell often uses UTF-16)
        text = None
        for encoding in ['utf-8-sig', 'utf-16', 'utf-16-le', 'utf-8', 'cp949']:
            try:
                text = content.decode(encoding)
                break
            except (UnicodeDecodeError, LookupError):
                continue

        if text is None:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Unable to decode file. Please save as UTF-8."
            )

        data = json.loads(text)
    except json.JSONDecodeError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Invalid JSON format: {str(e)}"
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Error reading file: {str(e)}"
        )

    # Validate required fields
    required_fields = ['asset_name', 'asset_type', 'results']
    for field in required_fields:
        if field not in data:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Missing required field: {field}"
            )

    # Convert to AgentReport and process
    try:
        report = AgentReport(
            asset_name=data['asset_name'],
            asset_type=data['asset_type'],
            hostname=data.get('hostname'),
            ip_address=data.get('ip_address'),
            results=[CheckResult(**r) for r in data['results']],
            agent_version=data.get('agent_version', '1.0.0')
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Invalid report format: {str(e)}"
        )

    # Process the report using existing logic
    return await process_agent_report(report, db)


async def process_agent_report(report: AgentReport, db: Session) -> AgentReportResponse:
    """Common logic for processing agent reports."""
    errors = []
    processed = 0
    created = 0
    updated = 0

    # Find or create asset
    asset = db.query(Asset).filter(Asset.name == report.asset_name).first()

    if not asset:
        from app.models.asset import AssetType, Environment, Criticality

        asset_type_map = {
            "windows": AssetType.WINDOWS,
            "unix": AssetType.UNIX,
        }

        asset = Asset(
            name=report.asset_name,
            asset_type=asset_type_map.get(report.asset_type.lower(), AssetType.OTHER),
            hostname=report.hostname,
            ip_address=report.ip_address,
            environment=Environment.PRODUCTION,
            criticality=Criticality.MEDIUM,
        )
        db.add(asset)
        db.commit()
        db.refresh(asset)
    else:
        if report.hostname:
            asset.hostname = report.hostname
        if report.ip_address:
            asset.ip_address = report.ip_address
        db.commit()

    # Process each check result
    for result in report.results:
        try:
            checklist_item = db.query(ChecklistItem).filter(
                ChecklistItem.item_code == result.item_code
            ).first()

            if not checklist_item:
                errors.append(f"Unknown item code: {result.item_code}")
                continue

            status_map = {
                "pass": AssessmentStatus.PASS,
                "fail": AssessmentStatus.FAIL,
                "na": AssessmentStatus.NA,
                "error": AssessmentStatus.NOT_ASSESSED,
            }
            assessment_status = status_map.get(result.status.lower(), AssessmentStatus.NOT_ASSESSED)

            assessment = db.query(Assessment).filter(
                Assessment.asset_id == asset.id,
                Assessment.checklist_item_id == checklist_item.id
            ).first()

            if assessment:
                assessment.status = assessment_status
                if result.evidence:
                    assessment.evidence_note = result.evidence
                if result.check_command:
                    assessment.check_command = result.check_command
                if result.remediation_command:
                    assessment.remediation_command = result.remediation_command
                assessment.updated_at = datetime.utcnow()
                updated += 1
            else:
                assessment = Assessment(
                    asset_id=asset.id,
                    checklist_item_id=checklist_item.id,
                    status=assessment_status,
                    evidence_note=result.evidence,
                    check_command=result.check_command,
                    remediation_command=result.remediation_command,
                    assessor="agent",
                )
                db.add(assessment)
                created += 1

            processed += 1

        except Exception as e:
            errors.append(f"Error processing {result.item_code}: {str(e)}")

    db.commit()

    return AgentReportResponse(
        success=len(errors) == 0,
        asset_id=asset.id,
        processed=processed,
        created=created,
        updated=updated,
        errors=errors[:10]
    )
